stages:
  - version
  - buildPublish

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VERSION_FILE: version.sh
  GIT_DEPTH: 500
  DOCKER_VERSION: 19.03.12
  JDK_VERSION: 8.0.275.hs-adpt
  SBT_VERSION: 1.3.10
  BASE_IMAGE: jupyter/minimal-notebook:612aa5710bf9
  IMAGE_NAME: ds-notebook
  NAMESPACE_IMAGE_NAME: biodatageeks/${IMAGE_NAME}
  SERVICE_ACCOUNT: "ds-lab-sa"
  HUB_IMAGE_NAME: ds-hub
  HUB_BASE_IMAGE: jupyterhub/k8s-hub:0.9.1
  GSUTIL_VERSION: "4.55"
  MLFLOW_VERSION: 1.12.1
  MLFLOW_ENABLED: "false"
  AUTO_BUCKET_ENABLED: "false"

.defaultImageVars: &defaultImageVars
  SPARK_VERSION: "3.0.1"
  SPARK_IMAGE: "biodatageeks/spark-py:v3.0.1"
  PYTHON_MINOR: "3.7"
  SCALA_VERSION: 2.12.10
  JUPYTER_KERNEL_NAME: datascience
  MLFLOW_ENABLED: "true"
  AUTO_BUCKET_ENABLED: "true"
  NOTEBOOKS_REPO: https://github.com/biodatageeks/ds-notebooks


.spark24ImageVars: &spark24ImageVars
  SPARK_VERSION: "2.4.3"
  SPARK_IMAGE: "biodatageeks/spark-py:v2.4.3-3.6.9"
  PYTHON_MINOR: "3.6.9"
  SCALA_VERSION: 2.11.12
  JUPYTER_KERNEL_NAME: pysequila
  MLFLOW_ENABLED: "true"
  AUTO_BUCKET_ENABLED: "true"
  NOTEBOOKS_REPO: https://github.com/biodatageeks/notebooks


.edugenImageVars: &edugenImageVars
  JDK_VERSION: 11.0.9.hs-adpt
  SPARK_VERSION: "3.0.1"
  SPARK_IMAGE: "biodatageeks/spark-py:v3.0.1"
  PYTHON_MINOR: "3.7"
  SCALA_VERSION: 2.12.10
  JUPYTER_KERNEL_NAME: edugen
  MLFLOW_ENABLED: "false"
  AUTO_BUCKET_ENABLED: "false"
  NOTEBOOKS_REPO: https://github.com/IMID/edugen_pub

# --------------------------------- STAGE: version ---------------------------------------------------------------------
version-branch:
  stage: version
  image:
    name: mdomke/git-semver:v4.0.1
    entrypoint: [""]
  script:
    - cd /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME && git-semver --format x.y.z+m | sed 's/+/-/g' | xargs -I {} echo "export VERSION={}" > $VERSION_FILE
    - cat $VERSION_FILE
  artifacts:
    paths:
      - $VERSION_FILE
  tags: [ docker ]
  except: [ main, tags ]

version-tag:
  stage: version
  image:
    name: mdomke/git-semver:v4.0.1
    entrypoint: [""]
  script:
    - cd /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME && git-semver --no-hash --no-pre | xargs -I {} echo "export VERSION={}" > $VERSION_FILE
    - cat $VERSION_FILE
  artifacts:
    paths:
      - $VERSION_FILE
  tags: [ docker ]
  only:
    - tags
  except:
    - branches

.buildPublish: &buildPublish
  image:
    name: docker:$DOCKER_VERSION
  before_script:
    - source $VERSION_FILE
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD docker.io
  script:
    - cd $IMAGE_NAME/
    - docker build
      --pull
      --build-arg BASE_IMAGE=$BASE_IMAGE
      --build-arg JAVA_VERSION=$JDK_VERSION
      --build-arg SCALA_VERSION=$SCALA_VERSION
      --build-arg SBT_VERSION=$SBT_VERSION
      --build-arg SPARK_VERSION=$SPARK_VERSION
      --build-arg NOTEBOOKS_REPO=$NOTEBOOKS_REPO
      --build-arg JUPYTER_KERNEL_NAME=$JUPYTER_KERNEL_NAME
      --build-arg PYTHON_MINOR=$PYTHON_MINOR
      --build-arg SERVICE_ACCOUNT=$SERVICE_ACCOUNT
      --build-arg SPARK_IMAGE=$SPARK_IMAGE
      --build-arg GSUTIL_VERSION=$GSUTIL_VERSION
      --build-arg MLFLOW_VERSION=$MLFLOW_VERSION
      --build-arg MLFLOW_ENABLED=$MLFLOW_ENABLED
      --build-arg AUTO_BUCKET_ENABLED=$AUTO_BUCKET_ENABLED
      -t $NAMESPACE_IMAGE_NAME:spark-$JUPYTER_KERNEL_NAME-$SPARK_VERSION-$VERSION
      .
    - docker push $NAMESPACE_IMAGE_NAME:spark-$JUPYTER_KERNEL_NAME-$SPARK_VERSION-$VERSION
  tags: [ docker ]



buildPublishDefault:
  stage: buildPublish
  variables:
    <<: *defaultImageVars
  <<: *buildPublish
  except: [ main ]

buildPublish24:
  stage: buildPublish
  variables:
    <<: *spark24ImageVars
  <<: *buildPublish
  except: [ main ]

buildPublishEdugen:
  stage: buildPublish
  variables:
    <<: *edugenImageVars
  <<: *buildPublish
  except: [ main ]

buildPublishHub:
  stage: buildPublish
  variables:
    NAMESPACE_IMAGE_NAME: biodatageeks/${HUB_IMAGE_NAME}
  image:
    name: docker:$DOCKER_VERSION
  before_script:
    - source $VERSION_FILE
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD docker.io
  script:
    - cd ds-hub
    - docker build
      --pull
      --build-arg BASE_IMAGE=$HUB_BASE_IMAGE
      -t $NAMESPACE_IMAGE_NAME:$VERSION
      .
    - docker push $NAMESPACE_IMAGE_NAME:$VERSION
  tags: [ docker ]
  except: [ main ]